### ISSUE TITLE
Crops List

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/PlantTreatyInterdependence#4]
@ColinKhoury, I added the crops from CWR to Species List File (Google Drive). This file has some issues with some crops, I marked them with orange color in the crop's name.

Tea and mate ~ Tea
Tomatoes ~ Tomato
Grasspea ~ Grass pea/Common chickling

Can you check those issues and tell me what we are going to do?

**Comment by ColinKhoury** [comment]
@stevensotelo @danipilze I worked on the master species list (google drive) - suggesting a new column that we use as our standard across the project (Common_name_standard). I tried to be inclusive with our list and what data might be available to us, while eliminating duplicates. Let me know what you think.

**Comment by stevensotelo** [comment]
@ColinKhoury, The following crops are not in our list, however they are in faostat list:

Broad beans, horse beans, dry
Coir
Oil, kapok
Maple sugar and syrups

**Comment by ColinKhoury** [comment]
Hi, 
Please see new version of allcrops list sending to you by email now. Coir = coconut; Broad beans = Faba beans; oil, Kapok = Kapok etc.
