### ISSUE TITLE
FAOstat Measures - Countries

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/PlantTreatyInterdependence#5]
@ColinKhoury, some records, which are from faostat database, have regions instead of countries. We don't have a way to split that records in countries. What should we do with that records?

![image](https://user-images.githubusercontent.com/4921829/47097046-26ec9900-d1f6-11e8-9cbd-0d7cc1955fc5.png)

**Comment by ColinKhoury** [comment]
We should make categories for all 'countries' - either 'country', 'region' or 'special group' as per FAOSTAT. Lets keep all data for all categories, but remember not to include all these things together when analyzing. WORLD should go into regions, probably
