### ISSUE TITLE
get data from Mansfeld

### ISSUE THREAD

**Issue by danipilze** [CIAT-DAPA/PlantTreatyInterdependence#6]
I made a Web Scrapping script in python to get the data
https://github.com/CIAT-DAPA/PlantTreatyInterdependence/blob/dev/src/Python/Mansfeld_scraper/main.py

It took les than 5min to execute
`species.csv: 100%|██████████| 144/144 [04:39<00:00,  1.69s/it]`

you can see all the records here
https://github.com/CIAT-https://github.com/CIAT-DAPA/PlantTreatyInterdependence/blob/dev/src/Python/Mansfeld_scraper/mansfeld.species.csv

now I'm trying to get the crop on which this species are related with using the common name

cc @ColinKhoury @stevensotelo

**Comment by ColinKhoury** [comment]
Great job! This looks very challenging. Are there no common names in Mansfeld?
Perhaps make a list of uses and we can discuss which to include? we shouldnt include all of them

**Comment by danipilze** [comment]
Thanks!
yes, there are common names, but i need go another level of depth in the page
After taking different strategies to navigate the page, I found the correct way to make the script work so it shouldn't be hard to go deeper.

Sure, I'll expor the list, there are 144 uses to check.

**Comment by danipilze** [comment]
I implemented the scraping of common names

https://github.com/CIAT-DAPA/PlantTreatyInterdependence/blob/dev/src/Python/Mansfeld_scraper/mansfeld.species.csv

`mansfeld.species.csv: 100%|██████████| 144/144 [2:37:57<00:00, 60.86s/it]`
