### ISSUE TITLE
Records duplicate in faostat

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/PlantTreatyInterdependence#7]
@ColinKhoury 

I found one issue when we imported the data from faostat to the database. We are changing the crops name from faostat to our master crops file, when we change the names two or more crops would have the same crop name in our list, for example: 

![image](https://user-images.githubusercontent.com/4921829/47530250-b0900c80-d86f-11e8-95aa-c73bf21606a1.png)

| faostat          | master crops |
| Beans, dry     | Beans |
| Beans, green | Beans |

It creates two records for the same crop with different values. What should we do with that records? 

I think that we have to sum the values and save only one record

**Comment by ColinKhoury** [comment]
Hi Stevie- yes, this is exactly the case where we need to sum the values
